### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by MOHAMMED1MEDHAT** [Skill-Sync/SkillSync-Backend#4]

**Comment by MOHAMMED1MEDHAT** [comment]
End Points:
-signup==>{}
-login==>{}
-

**Comment by MAES-Pyramids** [comment]
1-CreateAccessAndRefreshTokens Function, parameters (res, statusCode, userId)
2- Create AccessToken Function , parameters (res, statusCode, userId, sessionId)
